name: Test
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  test:
    name: 'Guardian e2e Tests'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm install

      - name: Install Playwright Browsers
        run: |
          npx playwright install

      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test --reporter=line

      - name: Report failure to Sentry
        if: failure()
        run: npm run sentry:alert
